#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xrandr --output Virtual1 --mode 1440x900 &
$HOME/.config/polybar/launch.sh &
picom -b &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Wallpapers/yCSsycL.jpg
